# Generated by Django 3.2.6 on 2021-08-18 18:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_date', models.DateField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('trans', models.IntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=9999), django.core.validators.MinValueValidator(limit_value=0)])),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('is_emailed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='InvoicePackage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_invoiced', models.BooleanField(default=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_warehouse.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Payer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=16)),
                ('last_name', models.CharField(max_length=16)),
                ('dob', models.DateField()),
                ('street', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=16)),
                ('state', models.CharField(max_length=2)),
                ('zip', models.CharField(max_length=5)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=128)),
            ],
            options={
                'unique_together': {('first_name', 'last_name', 'dob')},
            },
        ),
        migrations.CreateModel(
            name='ServiceTypeUnitPrice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('G', "Yida's Ground"), ('P', "Yida's Priority Overnight"), ('S', "Yida's Express Saver")], max_length=2)),
                ('desc', models.CharField(max_length=64)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SurchargeUnitPrice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('DI', 'Dry Ice'), ('WD', 'Weekend Delivery'), ('CC', 'Cold Chain'), ('PI', 'Package Indemnity')], max_length=2)),
                ('desc', models.CharField(max_length=64)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ZoneUnitPrice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('A', 'within Zone A'), ('B', 'within Zone B'), ('C', 'within Zone C'), ('AB', 'between Zone AB'), ('AC', 'between Zone AC'), ('BC', 'between Zone BC')], max_length=2)),
                ('desc', models.CharField(max_length=64)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('TrackingNum', models.CharField(max_length=32, unique=True)),
                ('ShipDate', models.DateField()),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('service_type', models.CharField(choices=[('G', "Yida's Ground"), ('P', "Yida's Priority Overnight"), ('S', "Yida's Express Saver")], max_length=2)),
                ('status', models.CharField(choices=[('D', 'Delivered'), ('W', 'Delay Due to Weather Condition'), ('I', 'In Transit'), ('P', 'Pending')], max_length=2)),
                ('PackageWeight', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ShipperStreet', models.CharField(max_length=32)),
                ('ShipperCity', models.CharField(max_length=16)),
                ('ShipperState', models.CharField(max_length=2)),
                ('ShipperZip', models.CharField(max_length=5)),
                ('RecipientStreet', models.CharField(max_length=32)),
                ('RecipientCity', models.CharField(max_length=16)),
                ('RecipientState', models.CharField(max_length=2)),
                ('RecipientZip', models.CharField(max_length=5)),
                ('is_imported', models.BooleanField(default=False)),
                ('payer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_warehouse.payer')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceSurcharge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('DI', 'Dry Ice'), ('WD', 'Weekend Delivery'), ('CC', 'Cold Chain'), ('PI', 'Package Indemnity')], max_length=2)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_warehouse.invoicepackage')),
            ],
        ),
        migrations.AddField(
            model_name='invoicepackage',
            name='shipment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_warehouse.shipment'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_warehouse.payer'),
        ),
    ]
