# Generated by Django 3.2.6 on 2021-08-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_warehouse', '0002_auto_20210820_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='RecipientCity',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='ShipperCity',
            field=models.CharField(max_length=32),
        ),
    ]
